### PR TITLE
add new screen for feedback & link to google form

### PR DESCRIPTION
**Pull request by doub1ejack**
Addresses issue #355 

Right now the feedback goes to this form in the [Code for BTV shared team drive](https://drive.google.com/open?id=1-PuPPAKDf8mN-9VKR_amjTji2LrUzIFjcAt-LWzuiDM).  However, if we want to, we could set this up to [generate new issues automatically](https://medium.com/@01010111/using-google-forms-to-submit-github-issues-efdb5f876b).

image

### CODE REVIEW

**Comment by johnneed** [comment]
We should not be adding new features at this stage.  We can hold this for next year.

**Review by johnneed — COMMENTED** [review]
This is not a feature that was on the board. We have been in feature freeze for some time,  Sorry but It can not be included in this year's app.

**Review by johnneed — CHANGES_REQUESTED** [review]
We are in feature freeze and cannot accept new features at this time.

**Comment by nfloersch** [comment]
I mis-interpreted this feature request. I thought the form shown was inside the app. 

Could the button not open an additional screen and directly open the Google Form?

Can we define who the feedback is for, and who gets access to it?

_If_ this is purely for our own input, we should make it very clear Green Up is not reviewing the form submissions. But, further, I think Green Up should know we are wanting to add a feedback option... because Kate may _want_ to collect feedback.

If the button directly opens a link in Chrome/Safari then the "feature" seems so minimal I wouldn't be worried about generating many new bugs. However, it still seems like a potential vector for bugs... I do not know enough about how Expo / React Native would open a URL to know the likelihood of new bugs showing up from opening a URL in an external app. I am expecting opening a URL in a 3rd party tool on the device is a one-liner. If it requires configuration and control over how the app handles switching over to the other app, and could cause the Green Up app to freeze while blocking perhaps...

So that is my input and concern.

**Comment by doub1ejack** [comment]
Closing this in favor of some changes @nfloersch made - including a "Donate" and a "Who Built This" button.  (Not sure what PR that is/was tho.)

**Pull request closed without merging**
