### PR TITLE
Issue 126

### PR DESCRIPTION
**Pull request by johnneed**
Added listeners and fixed other misc bugs I ran across.

we need some serious code clean-up :-(

### CODE REVIEW

**Comment by johnneed** [comment]
#126

**Comment by mfelix5** [comment]
@johnneed, when I test this, the invitee sees existing messages after s/he accepts an invitation to join a team. Based on my read of issue #126, this is the desired behavior and fixes the stated bug. However, I note that the team owner doesn't see the team messages until s/he logs out and logs back in.

to reproduce: as user A, create a new team. Send a message to the team. Invite user B to the team. As user B, log in, accept the invite and send a message to the team. User A doesn't see any messages until logging out and logging back in. 

expected behavior: User A sees messages s/he sends as well as the message user B sends immediately after they are sent. 

I don't see the issue in the code but assume this is related to a listener for the team owner.

**Comment by johnneed** [comment]
Yes this is probably the same sort of issue.  I'll create a seperate bug for that.  Go ahead and approve this and some one can fix the new bug later.

**Comment by mfelix5** [comment]
Ok, will approve and create a new issue for owner.

**Review by mfelix5 — APPROVED** [review]
LGTM

**Pull request merged**
