### PR TITLE
d fixed pickup loc undefined bug

### PR DESCRIPTION
**Pull request by johnneed**
'twas some incorrect property names.  The models changed when we moved to Firestore.   
Also fixed a margin issue in a modal window.

### CODE REVIEW

**Comment by johnneed** [comment]
https://github.com/codeforbtv/green-up-app/issues/121

**Comment by johnneed** [comment]
#121

**Comment by johnneed** [comment]
I just realized if I type #<issue number> that it creates a link to the issue.

**Review by mfelix5 — APPROVED** [review]
Looks good to me.

**Pull request merged**
