### PR TITLE
fixed offset pins

### PR DESCRIPTION
**Pull request by johnneed**
Fix for Issue #26 
Pins with same location are now offset slightly

### CODE REVIEW

**Comment by mfelix5** [comment]
@johnneed if I add two new trash drops in the same location, both are offset from my current position but placed on top of each other with no offset....

**Review by mfelix5 — COMMENTED** [review]
John, if I create a trash drop, it is offset slightly from my actual position. If I create a second trash drop, it is placed exactly on top of the first.

**Comment by johnneed** [comment]
@mfelix5 Right, this ticket was about supply pickup and trash dropoff locations.  TrashDrops are another matter.  Perhaps we should create a new ticket for that.  

If you want to test this, try looking at Westford, Pickup and Dropoff locations they are the same address but should now be slightly offset.

**Comment by mfelix5** [comment]
ok, got it. I'll try to look at this later tonight.

**Review by smara-codes — APPROVED** [review]

**Pull request merged**
